apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pvc-pv
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  hostPath:
    path: /root/cluster-data/minio-pvc-v4
    type: DirectoryOrCreate
  claimRef:
    namespace: kubeflow
    name: minio-pvc
