apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-claim-pv
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  hostPath:
    path: /root/cluster-data/mysql-pv-claim-v3
    type: DirectoryOrCreate
  claimRef:
    namespace: kubeflow
    name: mysql-pv-claim
