apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow-user-example-com
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trading-engine-sa
  namespace: kubeflow-user-example-com
